src/Entity/Dive.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;

/**
 * @ORM\Entity(repositoryClass="App\Repository\DiveRepository")
 */
class Dive
{
    /**
     * -----------------------
     * -------CONSTANTS-------
     * -----------------------
     */

    const DIVETYPE = [
    0 => 'Technique',
    1 => 'Exploration'
    ];

    /**
     * ------------------------
     * -------ATTRIBUTES-------
     * ------------------------
     */

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $location;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $dive_site;

    /**
     * @ORM\Column(type="integer")
     */
    private $max_depth;

    /**
     * @ORM\Column(type="integer")
     */
    private $dive_time;

    /**
     * @ORM\Column(type="boolean")
     */
    private $stops;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $stops_time;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $pre_dive_interval;

    /**
     * @ORM\Column(type="integer")
     */
    private $dive_type;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comments;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $stop_depth;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;


    /**
     * ------------------------
     * ---GETTER AND SETTERS---
     * ------------------------
     */

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function getFormatedDate() : string
    {
        return $this->getDate()->format('Y-m-d');
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(string $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getDiveSite(): ?string
    {
        return $this->dive_site;
    }

    public function setDiveSite(string $dive_site): self
    {
        $this->dive_site = $dive_site;

        return $this;
    }

    public function getMaxDepth(): ?int
    {
        return $this->max_depth;
    }

    public function setMaxDepth(int $max_depth): self
    {
        $this->max_depth = $max_depth;

        return $this;
    }

    public function getDiveTime(): ?int
    {
        return $this->dive_time;
    }

    public function setDiveTime(int $dive_time): self
    {
        $this->dive_time = $dive_time;

        return $this;
    }

    public function getStops(): ?bool
    {
        return $this->stops;
    }

    public function setStops(bool $stops): self
    {
        $this->stops = $stops;

        return $this;
    }

    public function getStopsTime(): ?int
    {
        return $this->stops_time;
    }

    public function setStopsTime(?int $stops_time): self
    {
        $this->stops_time = $stops_time;

        return $this;
    }

    public function getPreDiveInterval(): ?int
    {
        return $this->pre_dive_interval;
    }

    public function setPreDiveInterval(?int $pre_dive_interval): self
    {
        $this->pre_dive_interval = $pre_dive_interval;

        return $this;
    }

    public function getDiveType(): ?int
    {
        return $this->dive_type;
    }

    public function getDiveTypeFormated(): string
    {
        return self::DIVETYPE[$this->dive_type];
    }

    public function setDiveType(int $dive_type): self
    {
        $this->dive_type = $dive_type;

        return $this;
    }

    public function getComments(): ?string
    {
        return $this->comments;
    }

    public function setComments(?string $comments): self
    {
        $this->comments = $comments;

        return $this;
    }

    public function getStopDepth(): ?int
    {
        return $this->stop_depth;
    }

    public function setStopDepth(?int $stop_depth): self
    {
        $this->stop_depth = $stop_depth;

        return $this;
    }

    public function getSlug(): string
    {
        return (new Slugify())->slugify($this->getTitle());
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

}

src/Form/DiveType.php
<?php

namespace App\Form;

use App\Entity\Dive;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class DiveType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('date')
            ->add('location')
            ->add('dive_site')
            ->add('max_depth')
            ->add('dive_time')
            ->add('stops')
            ->add('stops_time')
            ->add('pre_dive_interval')
            ->add('dive_type', ChoiceType::class, [
                'choices' => array_flip(Dive::DIVETYPE)
            ])
            ->add('comments')
            ->add('stop_depth')
            ->add('title')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Dive::class,
            'translation_domain' => 'forms'
        ]);
    }
}

src/Controller/DiveController.php
<?php
namespace App\Controller;


use App\Entity\Dive;
use App\Repository\DiveRepository;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class DiveController extends AbstractController
{
    /**
     * @var DiveRepository
     */
    private $repository;

    /**
     * @var ObjectManager
     */
    private $em;

    /**
     * DiveController constructor.
     * @param DiveRepository $repo
     */
    public function __construct(DiveRepository $repo, ObjectManager $em)
    {
        $this->repository = $repo;
        $this->em = $em;
    }

    /**
     * @Route(path="/plongees", name="dive.index")
     * @return Response
     */
    public function index(DiveRepository $repository) : Response
    {
        $dive = new Dive();
        $dive = $this->repository->findAll();


        return $this->render('dive/index.html.twig',[
            'current_menu' => 'dives',
            'dives' => $dive
        ]);
    }

    /**
     * @Route(path="/plongees/{slug}-{id}", name="dive.show", requirements={"slug": "[a-z0-9\-]*"})
     * @return Response
     */
    public function show(Dive $dive, string $slug):Response
    {
        $slugFromObject = $dive->getSlug();

        //Redirection
        if($slugFromObject !== $slug) {
            return $this->redirectToRoute('dive.show', [
                'id' => $dive->getId(),
                'slug' => $slugFromObject
            ], 301);
        }

        return $this->render('dive/show.html.twig', [
            'current_menu' => 'dives',
            'dive' => $dive
        ]);
    }



}

templates/dive/index.html.twig
{%  extends 'base.html.twig'%}

{% block body %}
    <div class="container mt-4 text-center">
        <h1>Plongées</h1>

    </div>
    <div class="container mt-4">
        <h2>Mes Plongées</h2>

        <table class="table table-stripped">
            <thead>
            <tr>
                <th>Titre</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
            {% for dive in dives %}
                <tr>
                    <td>{{ dive.title }}</td>
                    <td>
                        <a href="{{ path('dive.show', {id: dive.id, slug: dive.slug}) }}" class="btn btn-secondary"> Voir</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>

        </table>



    </div>
{% endblock%}

templates/dive/show.html.twig
{%  extends 'base.html.twig'%}
{% block title dive.title%}
{% block body %}

    <div class="jumbotron">
        <div class="container">
            <div class="row">
                <div class="col-md-8">

                </div>
                <div class="col-md-4">
                    <h1>{{ dive.title }}</h1>
                    <h2>{{ dive.formatedDate }}</h2>

                    <a href="#" class="btn btn-primary">Contacter l'organisme</a>
                </div>
            </div>
        </div>
    </div>

    <div class="container mt-4 ">

        <p>
            {{ dive.comments | nl2br }}
        </p>

        <div class="row">
            <div class="col-md-8">
                <h2>Caractéristiques</h2>
                <table class="table table-striped">
                    <tr>
                        <td>Type de plongée</td>
                        <td>{{ dive.diveTypeFormated }}</td>
                    </tr>
                    <tr>
                        <td>Lieu</td>
                        <td>{{ dive.location }} </td>
                    </tr>
                    <tr>
                        <td>Site</td>
                        <td>{{ dive.diveSite }} </td>
                    </tr>
                    <tr>
                        <td>Durée</td>
                        <td>{{ dive.diveTime }} minutes</td>
                    </tr>
                    <tr>
                        <td>Profondeur max</td>
                        <td>{{ dive.maxDepth }} mètres</td>
                    </tr>
                    <tr>
                        <td>Palier(s)</td>
                        <td>{%  if dive.stops %} oui {% else %} non {% endif %} </td>
                    </tr>
                    <tr>
                        <td>Temps au palier</td>
                        <td>{%  if dive.stops %} {{ dive.stopsTime }} min {% endif %} </td>
                    </tr>
                    <tr>
                        <td>Profondeur palier</td>
                        <td>{%  if dive.stops %} {{ dive.stopDepth }} mètres {% endif %} </td>
                    </tr>
                </table>
            </div>
            <div class="col-md-4">
                <h2>Spécificités</h2>
            </div>
        </div>
    </div>

{% endblock %}